class X

	def main
		assert 5 in Object()  # .error. The right-hand expression for "in" is of type "Object" which contains nothing.
		
		t = [1, 2, 3]
		assert 'a' in t  # .error. cannot be "in" the right-hand expression because the left type
