# .error. cannot find
class Test

	def foo(other as Object)
		assert (other to UnknownClass).foo  # used to cause an internal exception
