class Test

	def populateList(t as List<of String>)  # used to cause an uncaught exception
		t.add('foo')
		t.add('bar')

	def main
		is shared
		
		t as Test = Test()
		t.populateList(List<of String>())
